Vagrant.configure(2) do |config|
  
  # create the master node
  config.vm.define "master" do |master01|
    master01.vm.box = "ubuntu/focal64"
    master01.vm.hostname = "Master"
    master01.vm.network "private_network", ip: "192.168.56.3"
    master01.vm.boot_timeout = 600
    master01.vm.provision "shell", path: "create_user_dir.sh"
    master01.vm.provision "shell", path: "lamp_stack.sh"
  end
  
  # create the slave node
  config.vm.define "slave" do |slave01|
    slave01.vm.box = "ubuntu/focal64"
    slave01.vm.hostname = "Slave"
    slave01.vm.network "private_network", ip: "192.168.56.4"
    slave01.vm.boot_timeout = 600
    slave01.vm.provision "shell", path: "lamp_stack.sh"
  end
  
  # create the loadbalancer
  config.vm.define "loadbal" do |loadbal01|
    loadbal01.vm.box = "ubuntu/focal64"
    loadbal01.vm.hostname = "loadbal"
    loadbal01.vm.network "private_network", ip: "192.168.56.5"
    loadbal01.vm.boot_timeout = 600
    loadbal01.vm.provision "shell", path: "loadbalancer.sh"
  end

end