Vagrant.configure(2) do |config|
  # config.hostmanger.enable = true
  # config.hostmanger.manage_host = true
  
  # config.vm.define "master" do |master01|
  #   master01.vm.box = "ubuntu/focal64"
  #   master01.vm.hostname = "Master"
  #   master01.vm.network "private_network", ip: "192.168.56.3"
  #   # master01.vb.memory "512"
  #   # master01.vm.provision "shell", path: "nginx.sh"
  # end

  # config.vm.define "slave" do |slave01|
  #   slave01.vm.box = "ubuntu/focal64"
  #   slave01.vm.hostname = "Slave"
  #   slave01.vm.network "private_network", ip: "192.168.56.4"
  #   # slave01.vb.memory "512"
  #   # master01.vm.provision "shell", path: "nginx.sh"
  # end
  
  # config.vm.define "loadbal" do |loadbal01|
  #   loadbal01.vm.box = "ubuntu/focal64"
  #   loadbal01.vm.hostname = "loadbal"
  #   loadbal01.vm.network "private_network", ip: "192.168.56.5"
  #   # loadbal01.vb.memory "512"
  #   # master01.vm.provision "shell", path: "nginx.sh"
  # end

 
end