Vagrant.configure(2) do |config|
  # config.hostmanger.enable = true
  # config.hostmanger.manage_host = true
  
  # config.vm.define "master" do |master01|
  #   master01.vm.box = "ubuntu/focal64"
  #   master01.vm.hostname = "Master"
  #   master01.vm.network "private_network", ip: "192.168.56.3"
  #   master01.vm.provision "shell", path: "create_user.sh"
  #   master01.vm.provision "shell", path: "lamp_stack.sh"
  # end
  
  # config.vm.define "slave" do |slave01|
  #   slave01.vm.box = "ubuntu/focal64"
  #   slave01.vm.hostname = "Slave"
  #   slave01.vm.network "private_network", ip: "192.168.56.4"
  #   slave01.vm.provision "shell", path: "lamp_stack.sh"
  # end
  
  # config.vm.define "loadbal" do |loadbal01|
  #   loadbal01.vm.box = "ubuntu/focal64"
  #   loadbal01.vm.hostname = "loadbal"
  #   loadbal01.vm.network "private_network", ip: "192.168.56.5"
  #   loadbal01.vm.provision "shell", path: "loadbalancer.sh"
  # end
  
  # config.vm.define "tested" do |tested01|
  #   tested01.vm.box = "ubuntu/focal64"
  #   tested01.vm.hostname = "tested"
  #   tested01.vm.network "private_network", ip: "192.168.56.7"
  #   tested01.vm.boot_timeout = 600
  #   loadbal01.vm.provision "shell", path: "loadbalancer.sh"
  # end

  config.vm.define "tester" do |tester|
    tester.vm.box = "ubuntu/focal64"
    tester.vm.hostname = "tester"
    tester.vm.network "private_network", ip: "192.168.56.8"
    tester.vm.boot_timeout = 600
    tester.vm.provision "shell", path: "lamp_stack.sh"
  end
end