---
- name: Configure Server with Apache, Install PHP, Create index.php, and Restart Apache
  hosts: 127.0.0.1
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
      tags:
        - apache

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes
      tags:
        - apache

    - name: Install PHP and Apache PHP module
      apt:
        name: "{{ item }}"
      loop:
        - php
        - libapache2-mod-php
      tags:
        - php

    - name: Set Timezone to Africa/Lagos
      command: timedatectl set-timezone Africa/Lagos

    - name: Create index.php file
      copy:
        content: |
          <?php
          echo "Current server time in Africa/Lagos: " . date("F d, Y h:i:s A e", time());
          ?>
        dest: /var/www/html/index.php