name: build

on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone the repo
        uses: actions/checkout@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: show dir
        run: pwd


        
      # - name: Build Docker Image
      #   run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$REPOSITORY_NAME:$GITHUB_RUN_NUMBER
      
      # - name: Push Docker Image to Docker Hub
      #   run: docker push $DOCKERHUB_USERNAME/$REPOSITORY_NAME:$GITHUB_RUN_NUMBER